spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.95.7.37:3306/seata?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: EAy75mgwk9Bzs3!
  application:
    name: examples-order
  cloud:
    nacos:
      discovery:
        server-addr: 47.95.7.37:8848
        group: SEATA_GROUP
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


seata:
  enabled: true
  application-id: ${spring.application.name}
  # ?????????my_test_tx_group??????????
  tx-service-group: spring-cloud-dubbo-seata-service-group
  enable-auto-data-source-proxy: false
  service:
    # 1.0.0???vgroup_mapping
    vgroupMapping:
      # ?????????my_test_tx_group??????????
      spring-cloud-dubbo-seata-service-group: default
    grouplist:
      default: 47.95.7.37:8091
    enable-degrade: false
    disable-global-transaction: false
  store:
    mode: file
    file:
      dir: sessionStore
      max-branch-session-size: 16384
      max-global-session-size: 512
      file-write-buffer-cache-size: 16384
      session-reload-read-size: 100
      flush-disk-mode: async
    db:
      datasource: druid
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.95.7.37:3306/seata?useUnicode=true&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
      user: root
      password: EAy75mgwk9Bzs3!
      min-conn: 5
      max-conn: 100
      global-table: global_table
      branch-table: branch_table
      lock-table: lock_table
      distributed-lock-table: distributed_lock
      query-limit: 100
      max-wait: 5000
  config:
    type: nacos
    nacos:
      server-addr: 47.95.7.37:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
      namespace:
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 47.95.7.37:8848
      group: SEATA_GROUP
      cluster: default
      namespace:
      username: "nacos"
      password: "nacos"

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    #    id: zk-registry
    address: nacos://47.95.7.37:8848
server:
  port: 8802