spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order?allowMultiQueries=true
    driver-class-name:
server:
  port: 9091

