seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: spring-cloud-dubbo-seata-service-group
#  enable-auto-data-source-proxy: false # 千万别加
  service:
    vgroupMapping:
      spring-cloud-dubbo-seata-service-group: default
    grouplist:
      default: 47.95.7.37:8091
    enable-degrade: false
    disable-global-transaction: false
  store:
    mode: file
    file:
      dir: sessionStore
      max-branch-session-size: 16384
      max-global-session-size: 512
      file-write-buffer-cache-size: 16384
      session-reload-read-size: 100
      flush-disk-mode: async
  config:
    type: nacos
    nacos:
      server-addr: 47.95.7.37:8848
      group: SEATA_GROUP
      username: "nacos"
      password: "nacos"
      namespace:
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 47.95.7.37:8848
      group: SEATA_GROUP
      cluster: default
      namespace:
      username: "nacos"
      password: "nacos"

dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://47.95.7.37:8848

server:
  port: 8804
spring:
  application:
    name: examples-business
  cloud:
    nacos:
      discovery:
        server-addr: 47.95.7.37:8848
        group: SEATA_GROUP