spring:
  security:
    oauth2:
      client:
        registration:
          wechat:
            # 可以去试一下沙箱
            # 公众号服务号 appid
            client-id: wx9a3c276f9bdcaedc
            # 公众号服务号 secret
            client-secret: 69b32b0eb9698aeb6a7a4cf075f03b83
            # oauth2 login 用 '{baseUrl}/login/oauth2/code/{registrationId}' 会自动解析
            # oauth2 client 写你业务的链接即可
            authorization-grant-type: authorization_code
            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            # http://localhost:8082/login/oauth2/code/gitee
            scope: snsapi_userinfo
        provider:
          wechat:
            authorization-uri: https://open.weixin.qq.com/connect/oauth2/authorize
            token-uri: https://api.weixin.qq.com/sns/oauth2/access_token
            user-info-uri: https://api.weixin.qq.com/sns/userinfo
server:
  port: 8082