spring:
  datasource:
    driver-class-name: org.h2.Driver
    # h2 \u5185\u5B58\u6570\u636E\u5E93 \u5185\u5B58\u6A21\u5F0F\u8FDE\u63A5\u914D\u7F6E \u5E93\u540D: spring_security  mysql\u6A21\u5F0F
    url: jdbc:h2:mem:spring_security #;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  h2:
    #    \u5F00\u542Fconsole \u8BBF\u95EE \u9ED8\u8BA4false
    console:
      enabled: true
      settings:
        #      \u5F00\u542Fh2 console \u8DDF\u8E2A \u65B9\u4FBF\u8C03\u8BD5  \u9ED8\u8BA4 false
        trace: true
        #      \u5141\u8BB8console \u8FDC\u7A0B\u8BBF\u95EE \u9ED8\u8BA4false
        web-allow-others: true
      #  h2 \u8BBF\u95EE\u8DEF\u5F84\u4E0A\u4E0B\u6587
      path: /h2-consol
  sql:
    init:
      # \u521D\u59CB\u5316\u6570\u636E\u8868 DDL
      schema-locations: classpath:sql/ddl.sql
      #  \u521D\u59CB\u5316\u6570\u636E DML
      data-locations: classpath:sql/dml.sql
