spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-cloud-gateway-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.95.7.37:8848
    gateway:
      discovery:
        locator:
          enabled: true  # create routes by service ID automatically
          lower-case-service-id: true  # transfer to lower case
      routes:
        - id: spring-cloud-gateway-nacos-provider
          uri: lb://spring-cloud-gateway-nacos-provider #lb : loadbalance://
          predicates:
            - Path=/nacos/**
          filters:
            - StripPrefix=1 # exclude /nacos/

server:
  port: 8084
