spring:
  datasource:
    url: jdbc:mysql://47.95.7.37:3306/mybatis?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: EAy75mgwk9Bzs3!
