dubbo:
  registry:
    address: nacos://47.95.7.37:8848
  #    id: zk-registry
#    address: zookeeper://47.95.7.37:2181
  protocol:
    name: dubbo
    port: -1
  application:
    name: springboot-consumer
#  config-center:
#    address: zookeeper://47.95.7.37:2181
server:
  port: 8082