spring:
  datasource:
    url: jdbc:mysql://47.95.7.37:3306/mybatis
    username: root
    password: EAy75mgwk9Bzs3!

mybatis:
  # discovery mapper dir automatically
  mapper-locations: classpath:mapper/*.xml
  # discovery model automatically to ignore package prefies when witing xml files
  type-aliases-package: com.xjjlearning.database.mysql.model
  configuration:
    # map user_name to userName for shorting configuration file
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.xjjlearning.database.mysql.type.EnabledTypeHandler
    # show debug info in console
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081
#  config-location: