spring:
  security:
    oauth2:
      client:
        registration:
          xjj:
            client-id: xjj
            client-secret: secret
            #            isValidRedirectUri
            #            http://127.0.0.1:8082/oauth2/authorization/xjj
            #todo        redirect-uri:  '{baseUrl}/foo/bar' 错误的写法  根据oauth2协议localhost不可被解析
            #            redirect-uri:  '{baseUrl}/login/oauth2/code/{registrationId}'
            redirect-uri:  'http://127.0.0.1:8082/login/oauth2/code/{registrationId}'
#            redirect-uri: http://127.0.0.1:8082/foo/bar
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            scope: message.read,message.write,USERINFO
        provider:
          xjj:
            #todo       provider 尽量用域名  不要用localhost或者IP  而且要和well-known接口中保持一致
            issuer-uri: http://localhost:9000
            user-info-uri: http://localhost:9000/oauth2/user
            user-name-attribute: name