spring:
  cloud:
    gateway:
#      filter:
#        request-rate-limiter:
#          deny-empty-key: true   #限流器的key为null时返回403
#          enabled: true
      routes:
        - id: define_filter
          uri: http://localhost:8081/say
          predicates:
            - Path=/gateway/**
          filters:
            - name: GpDefine
              args:
                name: Gp_Mic
            - name: RequestRateLimiter
              args:
                denyEmptyKey: false
                emptyKeyStatus: SERVICE_UNAVAILABLE
                keyResolver: '#{@ipAddressKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
            - StripPrefix=1
  redis:
    host: 192.168.0.115
    port: 6379

server:
  port: 8082

# actuator 监控
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
