dubbo:
  application:
    name: springboot-privider
  protocol:
    name: dubbo
    port: -1
  registry:
#    id: zk-registry
    address: nacos://127.0.0.1:8848
#    address: zookeeper://127.0.0.1:2181
#  config-center:
#    address: zookeeper://127.0.0.1:2181
